### ISSUE TITLE
Run the server without root rights

### ISSUE THREAD

**Issue by jjpe** [drpain/blink-server#7]
Running code as root is a redonculous security risk, and for me, a bluetooth server it's a little hard to justify.
What are the current causes for needing root rights, and could you remove the necessity for root?

**Comment by Rudis1261** [comment]
Hi @jjpe, Last time I checked / used this. You had to run as root to be able to read the bluetooth streams. I am not sure whether that is still a requirement. And not sure what running this as root will give you? 

What the security risk is, it's pretty dependant on pairing the device. Unless you are able to get in somehow via a snoop or something.

You can try and run it without the sudo command and seeing whether it still works. If it does, then that solves your concern

**Comment by Rudis1261** [comment]
Ahh just looked at it, it's to be able to bind to the bluetooth socket. Like I said it used to be an issue, lemme know if it doesn't faceplant without that anymore
